server:
    port: 80

spring:
    application:
        name: microservice-consumer #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
eureka:
    client:
        registerWithEureka: true # 服务注册开关
        fetchRegistry: true # 服务发现开关
        serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
            defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
    instance:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true