server:
  port: 7001
spring:
  application:
    name: microservice-zuul-gateway
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka

zuul:
  routes:
    provider-product: # 路由名称，名称任意，路由名称唯一
      path: /productservice/** # 访问路径
      serviceId: microservice-product # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: true # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
  # 如果多个服务需要经过路由，则同povider-product方式继续添加，例如：
    provider-consumer:
      path: /consumer/**
      serviceId: microservice-consumer
      stripPrefix: false
